### ISSUE TITLE
[Bug] Thaumcraft support completely broken in 0.8.1

### ISSUE THREAD

**Issue by Dallandra** [jaredlll08/ModTweaker2#136]
As the title suggests, Thaumcraft support seems to not work at all with the most recent version. The scripts parse just fine, there are no errors... but nothing changes. Neither on /mt reload, world restart or full game restart. Even something as simple as changing the oak log aspects to ignis doesn't work.

Forge version is 10.13.2.1291
Thaumcraft 4.2.3.5
MineTweaker3 3.0.9C
ModTweaker2 0.8.1

**Comment by Dream-Master** [comment]
Use 0.8

**Comment by Dallandra** [comment]
That's still somehow bugged compared to way earlier versions like 0.6.0. Adding or changing anything research related now creates a NPE, which always looks like this.

java.lang.NullPointerException
	at modtweaker2.mods.thaumcraft.research.AddPrereq.apply(AddPrereq.java:33)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.thaumcraft.handlers.Research.addPrereq(Research.java:117)
	at Thaumcraft.__script__(thaumcraft.zs:8)
	at __ZenMain__.run(thaumcraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

The only difference is that AddPrereq in the very first line is replaced with either AddSibling or AddPage, depending on what is used (Parent or Sibling) or if Parent/Sibling is missing (so it goes straight to AddPage).

**Comment by talonos2** [comment]
Seconded. Thaumcraft research broken for me once I upgraded as well. 0.8.1 silently ignores all research commands.
