### ISSUE TITLE
Error With Blast Furnace Steel Recipe Removal

### ISSUE THREAD

**Issue by ubermentat** [jaredlll08/ModTweaker2#145]
Forge: 1388
MineTweaker: 3.0.9c
ModTweaker: 0.8.0 (0.8.1 reportedly breaks some integration)

When attempting to remove all methods of obtaining steel ingots with Railcraft's blast furnace except for using iron ingots/Garden Stuff's wrought iron ingots, minetweaker produces the following error:
```
ERROR: Error executing vanillaTools.zs: null
java.lang.NullPointerException
	at modtweaker2.mods.railcraft.handlers.BlastFurnace$Remove.apply(BlastFurnace.java:51)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.railcraft.handlers.BlastFurnace.removeRecipe(BlastFurnace.java:39)
	at VanillaTools.__script__(vanillaTools.zs:70)
	at __ZenMain__.run(vanillaTools.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```
This error only happens when attempting to add the iron/wrought iron to steel recipe. If I remove that line, the error goes away. Either way, the recipe removal doesn't work, and NEI still shows all of the usual recipes.

The lines I'm using are:
```
import mods.railcraft.BlastFurnace;
BlastFurnace.removeRecipe(<Railcraft:ingot:0>);
BlastFurnace.addRecipe(<minecraft:iron_ingot>, false, false, 1280, <Railcraft:ingot:0>);
```

**Comment by Yulife** [comment]
How did you do that code formatting thing? I need that in my life right now.
@jaredlll08 will look into it :)

**Comment by jaredlll08** [comment]
Uh no, no I will not be looking into it, I am taking my MUCH needed
off-time from the modding community.

**Comment by Yulife** [comment]
Then don't reply until you can work on it, punk.

**Comment by jaredlll08** [comment]
Don't say I can work on stuff when I can't ;)

**Comment by ubermentat** [comment]
@Yulife The code formatting is done through markdown. One ` formats a single line as code, and three ` both before and after a block will format the whole block as code.

**Comment by jaredlll08** [comment]
I believe that this may have been fixed by @Zixxl however I am in no condition to run the game right now to test :/ sorry

**Comment by Zixxl** [comment]
The bug should be fixed with the recent releases.
