### ISSUE TITLE
/mt recipes hand doesn't work

### ISSUE THREAD

**Issue by BakermanLP** [jaredlll08/ModTweaker2#163]
I am using the latest modtweaker2 version. Whenever I try to get the recipes with "/mt recipes hand" I get the following error:

[08:29:03] [Server thread/ERROR]: Couldn't process command: 'mt recipes hand'
java.lang.NullPointerException
	at minetweaker.mc1710.item.MCItemStack.matches(MCItemStack.java:250) ~[MCItemStack.class:?]
	at minetweaker.mc1710.recipes.MCRecipeManager.getRecipesFor(MCRecipeManager.java:63) ~[MCRecipeManager.class:?]
	at minetweaker.MineTweakerImplementationAPI$6.execute(MineTweakerImplementationAPI.java:212) ~[MineTweakerImplementationAPI$6.class:?]
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610) ~[MineTweakerImplementationAPI$19.class:?]
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124) ~[MCServer$MCCommand.class:?]
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94) [z.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739) [nh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718) [nh.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37) [ir.class:?]
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9) [ir.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111) [bsx.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [?:?]
[08:29:03] [Client thread/INFO]: [CHAT] An unknown error occurred while attempting to perform this command

**Comment by Voidi** [comment]
First what does that have to do with it ModTweaker? the Exception say nothing about modtweaker.
Second, as i know there is no command 'recipes hand'
There only 'minetweaker hand' and 'minetweaker recipes'.

**Comment by Dream-Master** [comment]
/mt hand
or
/minetweaker hand

show up the item in your hand.

**Comment by jaredlll08** [comment]
Close #163
Also not to mention. We will not be supporting scripts that se /mt reload.
