### ISSUE TITLE
TiCon/ExtraTiC SetAbility (or SetStyle)

### ISSUE THREAD

**Issue by Durpady** [jaredlll08/ModTweaker2#173]
I'm trying to tweak Void Metal and Fiery ExtraTiC materials to mirror their non-TiCon attributes, but I can't get the SetAbility commands to work.  I don't know if Self-Repair or Auto-Smelt can be added as innate material traits, but Shadow Iron has Weakness and Ignatius has Ignite, so those should be able to be added.  Actually, I can't get SetAbility to work at all, since I couldn't get it to give Modifiable to Wood as a test.  What am I doing wrong?  And what does SetStyle do?

mods.tconstruct.ToolStats.setAbility("Fiery", "Ignite");
mods.tconstruct.ToolStats.setAbility("Void Metal", "Weakness");
mods.tconstruct.ToolStats.setAbility("Wood", "Modifiable");

**Comment by damonmensch** [comment]
Personally I would assume setStyle determines which style of the part appears on the tool itself when rendered. As in the handle is the grey color of Stone.

When it comes to your setAbility, perhaps capitalization is your problem here. In the example on the wiki it says "stonebound" not "Stonebound" and I can assure you that in a coding stance capitalization is EVERYTHING, so I would suggest trying it in lowercase.

**Comment by Durpady** [comment]
"Writable", "writable", and even "writeable" don't work.  Capitalization isn't the issue.  I think that setAbility is just not working, period.
Mod versions are:
TiCon 1.8.5
ExtraTiC 1.4.5
MineTweaker 3.0.9C
ModTweaker 0.8.3
Forge 10.13.4.1448

**Comment by jaredlll08** [comment]
Can I get the error log?

**Comment by Durpady** [comment]
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: ExtraTiC.zs:16: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:18: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:19: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:21: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:22: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:22: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:22: Could not resolve <TConstruct : metalPatern : 0>
INFO: Changing material stats field : + ability for Fiery
INFO: Changing material stats field : + ability for Void Metal
INFO: Changing material stats field : + ability for Wood
INFO: Adding Smeltery - Melting Recipe for :Native Iron Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Gold Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Copper Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Tin Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Silver Cluster
ERROR: Error executing ExtraTiC.zs: null
java.lang.NullPointerException
	at ExtraTiC.__script__(ExtraTiC.zs:16)
	at __ZenMain__.run(ExtraTiC.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:555)
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:859)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:91)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
INFO: Adding furnace recipe for <minecraft:rotten_flesh>
INFO: Adding recipe for Mossy Stone Bricks
INFO: Adding furnace recipe for <minecraft:stonebrick>
INFO: Adding minetweaker command tooltips
INFO: Adding minetweaker command entities
INFO: Adding minetweaker command research
INFO: Adding minetweaker command aspectList
INFO: Adding minetweaker command materials
INFO: Adding minetweaker command lexiconCategories
INFO: Adding minetweaker command lexiconPages
INFO: Adding minetweaker command botaniaBrews
INFO: Adding minetweaker command lexiconKnowledgeTypes
INFO: Adding minetweaker command botaniaOrchid
INFO: Removing minetweaker command botaniaOrchid
INFO: Removing minetweaker command lexiconKnowledgeTypes
INFO: Removing minetweaker command botaniaBrews
INFO: Removing minetweaker command lexiconPages
INFO: Removing minetweaker command lexiconCategories
INFO: Removing minetweaker command materials
INFO: Removing minetweaker command aspectList
INFO: Removing minetweaker command research
INFO: Removing minetweaker command entities
INFO: Removing minetweaker command tooltips
INFO: Removing furnace recipe for <minecraft:stonebrick>
INFO: Removing recipe for Mossy Stone Bricks
INFO: Removing furnace recipe for <minecraft:rotten_flesh>
INFO: Removing Smeltery - Melting Recipe for :Native Silver Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Tin Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Copper Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Gold Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Iron Cluster
INFO: Undoing change of material stats field : + ability for Wood
INFO: Undoing change of material stats field : + ability for Void Metal
INFO: Undoing change of material stats field : + ability for Fiery
INFO: Removing minetweaker command mfr
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: ExtraTiC.zs:16: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:18: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:19: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:21: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:22: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:22: Could not resolve <liquid : red_aurum . molten>
INFO: Changing material stats field : + ability for Fiery
INFO: Changing material stats field : + ability for Void Metal
INFO: Changing material stats field : + ability for Wood
INFO: Adding Smeltery - Melting Recipe for :Native Iron Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Gold Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Copper Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Tin Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Silver Cluster
ERROR: Error executing ExtraTiC.zs: null
java.lang.NullPointerException
	at ExtraTiC.__script__(ExtraTiC.zs:16)
	at __ZenMain__.run(ExtraTiC.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
INFO: Adding furnace recipe for <minecraft:rotten_flesh>
INFO: Adding recipe for Mossy Stone Bricks
INFO: Adding furnace recipe for <minecraft:stonebrick>
INFO: Removing furnace recipe for <minecraft:stonebrick>
INFO: Removing recipe for Mossy Stone Bricks
INFO: Removing furnace recipe for <minecraft:rotten_flesh>
INFO: Removing Smeltery - Melting Recipe for :Native Silver Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Tin Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Copper Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Gold Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Iron Cluster
INFO: Undoing change of material stats field : + ability for Wood
INFO: Undoing change of material stats field : + ability for Void Metal
INFO: Undoing change of material stats field : + ability for Fiery
INFO: Removing minetweaker command mfr
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: ExtraTiC.zs:16: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:18: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:19: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:21: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:22: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:22: Could not resolve <liquid : red_aurum . molten>
INFO: Changing material stats field : + ability for Fiery
INFO: Changing material stats field : + ability for Void Metal
INFO: Changing material stats field : + ability for Wood
INFO: Adding Smeltery - Melting Recipe for :Native Iron Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Gold Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Copper Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Tin Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Silver Cluster
ERROR: Error executing ExtraTiC.zs: null
java.lang.NullPointerException
	at ExtraTiC.__script__(ExtraTiC.zs:16)
	at __ZenMain__.run(ExtraTiC.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
INFO: Adding furnace recipe for <minecraft:rotten_flesh>
INFO: Adding recipe for Mossy Stone Bricks
INFO: Adding furnace recipe for <minecraft:stonebrick>
INFO: Removing furnace recipe for <minecraft:stonebrick>
INFO: Removing recipe for Mossy Stone Bricks
INFO: Removing furnace recipe for <minecraft:rotten_flesh>
INFO: Removing Smeltery - Melting Recipe for :Native Silver Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Tin Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Copper Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Gold Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Iron Cluster
INFO: Undoing change of material stats field : + ability for Wood
INFO: Undoing change of material stats field : + ability for Void Metal
INFO: Undoing change of material stats field : + ability for Fiery
INFO: Removing minetweaker command mfr
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: ExtraTiC.zs:16: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:18: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:19: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:21: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:22: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:22: Could not resolve <liquid : red_aurum . molten>
INFO: Changing material stats field : + ability for Fiery
INFO: Changing material stats field : + ability for Void Metal
INFO: Changing material stats field : + ability for Wood
INFO: Adding Smeltery - Melting Recipe for :Native Iron Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Gold Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Copper Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Tin Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Silver Cluster
ERROR: Error executing ExtraTiC.zs: null
java.lang.NullPointerException
	at ExtraTiC.__script__(ExtraTiC.zs:16)
	at __ZenMain__.run(ExtraTiC.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
INFO: Adding furnace recipe for <minecraft:rotten_flesh>
INFO: Adding recipe for Mossy Stone Bricks
INFO: Adding furnace recipe for <minecraft:stonebrick>
INFO: Removing furnace recipe for <minecraft:stonebrick>
INFO: Removing recipe for Mossy Stone Bricks
INFO: Removing furnace recipe for <minecraft:rotten_flesh>
INFO: Removing Smeltery - Melting Recipe for :Native Silver Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Tin Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Copper Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Gold Cluster
INFO: Removing Smeltery - Melting Recipe for :Native Iron Cluster
INFO: Undoing change of material stats field : + ability for Wood
INFO: Undoing change of material stats field : + ability for Void Metal
INFO: Undoing change of material stats field : + ability for Fiery
INFO: Removing minetweaker command mfr
INFO: Removing command minetweaker
INFO: Adding command minetweaker
INFO: Adding minetweaker command mfr
ERROR: ExtraTiC.zs:16: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:18: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:19: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:21: Could not resolve <liquid : red_aurum . molten>
ERROR: ExtraTiC.zs:22: Could not resolve <ExtraTiC : ingotFunStuff : 2>
ERROR: ExtraTiC.zs:22: Could not resolve <liquid : red_aurum . molten>
INFO: Changing material stats field : + ability for Fiery
INFO: Changing material stats field : + ability for Void Metal
INFO: Changing material stats field : + ability for Wood
INFO: Adding Smeltery - Melting Recipe for :Native Iron Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Gold Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Copper Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Tin Cluster
INFO: Adding Smeltery - Melting Recipe for :Native Silver Cluster
ERROR: Error executing ExtraTiC.zs: null
java.lang.NullPointerException
	at ExtraTiC.__script__(ExtraTiC.zs:16)
	at __ZenMain__.run(ExtraTiC.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
INFO: Adding furnace recipe for <minecraft:rotten_flesh>
INFO: Adding recipe for Mossy Stone Bricks
INFO: Adding furnace recipe for <minecraft:stonebrick>

looking at the log myself, it says it's changing abilities, but looking at a tool in my hand, or a material in NEI, nothing is changed.

**Comment by jaredlll08** [comment]
Ok yea, that is ExtraTiC, not us. Sorry.

**Comment by Durpady** [comment]
Except that I can't seem to give Writable to Wood either.  Is ExtraTiC somehow stopping that?

**Comment by jaredlll08** [comment]
No, the actual minetweaker handler, is added voa TiC.

**Comment by jaredlll08** [comment]
Welp, ignore me. On mobile. No idea what is wrong, but it isn't ExtraTiC

**Comment by Zixxl** [comment]
Looks like the script has some errors and MineTweaker aborts loading the script. Can you pastebin ExtraTiC.zs?

**Comment by Durpady** [comment]
http://pastebin.com/CwXaJzWg
There's a lot of stuff in there for implementing Red Aurum, but the stuff you want is at the top.

**Comment by Yulife** [comment]
Calling @Glassmaker ;)

**Comment by blade1981m** [comment]
ToolStats.setAbility calls for the creation of a new ToolMaterial. Tinkers Construct changed their API so that when you create a new ToolMaterial ability is not one of the things you can pass into it anymore. They still have the old constructor but have it marked as deprecated, but it just falls through to the new constructor and doesn't actually do anything with the ability that was passed. I have not found a way in the new API to set an ability.

**Comment by blade1981m** [comment]
I did just find this - "Using deprecated addToolMaterial with ability name. ability will be ignored, use languages files for that." - not sure how much help it is, but figured I'd post it here in case it helps anyone else figure out how to set abilities.
