### ISSUE TITLE
Forestry Thermionic Fabricator load error (zs.null)

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#188]
@Zixxl 
With the last version I cant remove casts in Forestry. (Build 96 ok Build 100 not)
Did something change (i see only the log helper change in the Code history)

mods.forestry.ThermionicFabricator.removeCasts(<Forestry:thermionicTubes>);

````````````````````````````````````````````````````````````
ERROR: Error executing Forestry.zs: null
java.lang.NullPointerException
	at modtweaker2.helpers.LogHelper.getStackDescription(LogHelper.java:90)
	at modtweaker2.mods.forestry.handlers.ThermionicFabricator$RemoveCasts.getRecipeInfo(ThermionicFabricator.java:142)
	at modtweaker2.mods.forestry.handlers.ThermionicFabricator$RemoveCasts.getRecipeInfo(ThermionicFabricator.java:135)
	at modtweaker2.utils.BaseListModification.getRecipeInfo(BaseListModification.java:33)
	at modtweaker2.utils.BaseListRemoval.describe(BaseListRemoval.java:58)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:50)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.forestry.handlers.ThermionicFabricator.removeCasts(ThermionicFabricator.java:118)
	at Forestry.__script__(Forestry.zs:212)
	at __ZenMain__.run(Forestry.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI.onServerStart(MineTweakerImplementationAPI.java:555)
	at minetweaker.mc1710.MineTweakerMod.onServerAboutToStart(MineTweakerMod.java:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.serverAboutToStart(Loader.java:838)
	at cpw.mods.fml.common.FMLCommonHandler.handleServerAboutToStart(FMLCommonHandler.java:273)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callBoolean(Reflector.java:363)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:150)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
``````````````````````````````````````````````````

@jaredlll08  it is not a complain its only a simple question.

Thanks in advance.

**Comment by Zixxl** [comment]
I have a little Deja vu. Did i really broke the thermionic fabricator again? damn.

**Comment by Dream-Master** [comment]
Thanks works for me.

BTW somone know what that means?
ERROR: [ModTweaker2] Could not retrieve any static object for the provided field names.

I adiing Thaumcraft Aspects to Items
``````````````````````````````````````````
// --- Small Bone Segment
mods.thaumcraft.Aspects.set(<BiomesOPlenty:bones>, "corpus 1, exanimis 3, mortuus 2");

// --- Medium Bone Segment
mods.thaumcraft.Aspects.set(<BiomesOPlenty:bones:1>, "corpus 2, exanimis 6, mortuus 4");

// --- Large Bone Segment
mods.thaumcraft.Aspects.set(<BiomesOPlenty:bones:2>, "corpus 3, exanimis 9, mortuus 6");
````````````````````````````````````````````````

**Comment by Dream-Master** [comment]
Ah ok. Thanks
