### ISSUE TITLE
[1.7.10] Minor Mekanism Error

### ISSUE THREAD

**Issue by QORTEC** [jaredlll08/ModTweaker2#332]
There is a minor error/bug with ModTweaker2 0.9.5 and Mekanism 9.0.3.227, the error is found in fml-server-latest.log and doesn't crash the server.

Looking at the CurseForge page there hasn't been a update since late 2015, is 1.7.10 still receiving bug fixes or is it now unsupported?

Error:
````
[07:22:53] [Server thread/TRACE] [modtweaker2/modtweaker2]: Sending event FMLInitializationEvent to mod modtweaker2
[07:22:53] [Server thread/INFO] [modtweaker2/modtweaker2]: Starting Initialization for modtweaker2
java.lang.NoClassDefFoundError: mekanism/common/recipe/machines/SolarEvaporationRecipe
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at stanhebben.zenscript.type.ZenTypeNative.complete(ZenTypeNative.java:157)
	at minetweaker.runtime.GlobalRegistry.registerNativeClass(GlobalRegistry.java:101)
	at minetweaker.MineTweakerAPI.registerClass(MineTweakerAPI.java:336)
	at modtweaker2.mods.mekanism.Mekanism.<init>(Mekanism.java:44)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at modtweaker2.utils.TweakerPlugin.load(TweakerPlugin.java:18)
	at modtweaker2.utils.TweakerPlugin.register(TweakerPlugin.java:12)
	at modtweaker2.ModTweaker2.init(ModTweaker2.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.lang.ClassNotFoundException: mekanism.common.recipe.machines.SolarEvaporationRecipe
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at invtweaks.forge.asm.ContainerTransformer.transform(ContainerTransformer.java:112)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 49 more
[07:22:54] [Server thread/INFO] [STDOUT/modtweaker2]: [minetweaker.runtime.MTTweaker:load:111]: Loading scripts
[07:22:54] [Server thread/TRACE] [modtweaker2/modtweaker2]: Sent event FMLInitializationEvent to mod modtweaker2
[07:22:54] [Server thread/DEBUG] [FML/]: Bar Step: Initialization - Mod Tweaker 2 took 0.830s
````
removed ``[07:22:54] [Server thread/INFO] [STDERR/modtweaker2]: [java.lang.Throwable$WrappedPrintStream:println:748]: `` to make the error more readable

**Comment by jaredlll08** [comment]
We don't support 1.7.10 anymore AND we don't support mekanism 9.

**Comment by QORTEC** [comment]
Thank you
