### ISSUE TITLE
Remove inscriber recipe causes nullPointerException

### ISSUE THREAD

**Issue by AlexTheGre4t** [jaredlll08/ModTweaker2#69]
I used this code

var certusProcessor = <appliedenergistics2:item.ItemMultiMaterial:23>;
mods.appeng.inscriber.removeRecipe(certusProcessor);

Though i get this in the MT.log when reloading scripts

ERROR: Error executing AE2.zs: null
java.lang.NullPointerException
	at modtweaker2.mods.appeng.handlers.Inscriber$Remove.apply(Inscriber.java:58)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.appeng.handlers.Inscriber.removeRecipe(Inscriber.java:45)
	at AE2.__script__(AE2.zs:287)
	at __ZenMain__.run(AE2.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by jaredlll08** [comment]
Your script is wrong, it should be:

var certusProcessor = <appliedenergistics2:item.ItemMultiMaterial:23>;
mods.appeng.inscriber.removeRecipe(certusProcessor);

**Comment by AlexTheGre4t** [comment]
nope, still a nullpointer.

**Comment by jaredlll08** [comment]
did you build the latest version?, if you look, I closed this with a commit...

**Comment by AlexTheGre4t** [comment]
Got a build of latest commits, doing this code: 
mods.appeng.inscriber.removeRecipe(<appliedenergistics2:item:itemMultiMaterial:16);
mods.appeng.inscriber.removeRecipe(<appliedenergistics2:item:itemMultiMaterial:18);
mods.appeng.inscriber.removeRecipe(<appliedenergistics2:item:itemMultiMaterial:17);
mods.appeng.inscriber.removeRecipe(<appliedenergistics2:item:itemMultiMaterial:20);
mods.appeng.inscriber.removeRecipe(<appliedenergistics2:item:itemMultiMaterial:23);
mods.appeng.inscriber.removeRecipe(<appliedenergistics2:item:itemMultiMaterial:22);
mods.appeng.inscriber.removeRecipe(<appliedenergistics2:item:itemMultiMaterial:24);
for removing inscriber recipes gives a null pointer still :/ 
http://pastebin.com/YJw6uQef
