### ISSUE TITLE
Arcane Recipes Remove

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#72]
I want to remove Arcane Recipes but i cant. I get this error in the minetweaker log.
````````````````````````````````````````````````````````````````````````````````````````````````````````````````
ERROR: Error executing Thaumcraft.zs: null
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at modtweaker2.mods.thaumcraft.handlers.Arcane$Remove.apply(Arcane.java:60)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.thaumcraft.handlers.Arcane.removeRecipe(Arcane.java:50)
	at Thaumcraft.__script__(Thaumcraft.zs:97)
	at __ZenMain__.run(Thaumcraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`
````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

**Comment by Yulife** [comment]
It would help if you supply the script.

**Comment by Dream-Master** [comment]
https://github.com/Dream-Master/DreamCraft/blob/master/scripts/Thaumcraft.zs

**Comment by Dream-Master** [comment]
Die Zeil wird nicht benötigt 
import mods.thaumcraft.Arcane;

Bei Version 6 konnte ich noch Arcane Scripts removen jetzt wirft der nur noch Fehler raus.

Super das ihr jetzt Forestry unterstützt.

**Comment by Dream-Master** [comment]
Hab ne Lösung gefunden. Ich überschreibe das Rezept mit einen Nonsens Rezept. (6 Copper Nuggets geben ein Copper nugget) und dann geht es. Komisch. Wird zeit das ich mich noch mehr in java reinknie um Probleme besser zu lösen. Ich lass es offen vielleicht gibt es ja noch einen bessere Lösung als diesen Hack.

**Comment by Yulife** [comment]
Könntest du raussuchen welches Rezept-Removal genau den Error verursacht? Das würde es leichter machen.

-------------

Could you track down which recipe removal causes the error? That would make it more easy.

**Comment by Dream-Master** [comment]
Nur bei Arcanen  Rezepten. Aber wie gesagt wenn ich die überschreibe und Refreshe sind die weg. Brauche den Remove Code nicht. Azanor schrieb dazu folgendes: 

https://github.com/Azanor/thaumcraft/issues/1539
https://github.com/Azanor/thaumcraft/issues/1532


Only with Arcane Recipes. But if i override the recipes (with the same recipes) i not need the remove code. Azanor writing something when i posting this error:

**Comment by Dream-Master** [comment]
Wenn es nur so geht wurschtel ich mich da durch. Ist zwar nicht die beste Lösung aber wenigstens eine.

**Comment by jaredlll08** [comment]
English or I cant help...

**Comment by Dream-Master** [comment]
Yes sure my fault.

I try to explain my problem.
If you have a Arcane Table Recipe (Copper Wand Caps) you cant delete it (mods.thaumcraft.Arcane.removeRecipe) it throw out the code in my first post. Now i try to override the Recipe with a new one and refreshing the research. Now you have both Recipe (the old one and the new one) after i override the old recipes with the same ingredient (copper nugets )like the orginal and link it to a item like dirt or something else (using 1000 vis each aspeck that no one use this recipe) it worked showing my new recipe from the Copper Wand Cap (and the fake Recipe with the expensive Dirt) After this i can add the line "mods.thaumcraft.Arcane.removeRecipe...." and there is no error any more.
i see you didnt change any thing in the code only rename it to modtweaker 2. So i dont know what happend. 

I asking Azanor some weeks ago about this thing and he give me this answer:

https://github.com/Azanor/thaumcraft/issues/1532

https://github.com/Azanor/thaumcraft/issues/1532

**Comment by Dream-Master** [comment]
Bdw. I don't want to complain about anything you continue this mod and make a good jobs. Thanks

**Comment by Yulife** [comment]
I shall test when I get back home. Thanks for the report.

**Comment by Yulife** [comment]
As Azanor already said - this isn't possible. Jared will probably remove the dead code. Sorry!

**Comment by Dream-Master** [comment]
Ok than i  create a fake item in my core mod and override all recipes. Ok many things to do. 
Thanks for help.

**Comment by Yulife** [comment]
Maybe TPPITweaks is able to do it? Calling @tterrag1098

**Comment by Dream-Master** [comment]
Thanks.

Another Question. (i wrote in Minetweaker git too) is it possible to update Gt to Version 5 /6 and add Fluid support because Stan not working on the mod since a while.

**Comment by tterrag1098** [comment]
Heh, nope

**Comment by Dream-Master** [comment]
?

**Comment by tterrag1098** [comment]
> Maybe TPPITweaks is able to do it? Calling @tterrag1098

**Comment by Dream-Master** [comment]
But it isnt right ?

**Comment by tterrag1098** [comment]
I was saying no, I don't have a way around this.

**Comment by Dream-Master** [comment]
@jaredlll08 
I see you working on the  Arcane Handlers. That mean this bug get to be fixed ?

**Comment by Yulife** [comment]
For some items yes, for some items no.
