### ISSUE TITLE
[bug] Add Carpenters Recipes

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#76]
I try to add a recipes to the Carpenter (with seedoil) and it dont work. 
``````````````````````````````````````````````````````````````````````````````````````````````````````````
ERROR: Forestry.zs:171: Could not resolve <fluid : seedoil>
ERROR: Forestry.zs:171 > a method available but none matches the parameters (int, any, any[], minetweaker.item.IItemStack)
````````````````````````````````````````````````````````````````````````````````````````````````````````````````
i remove the recipes and it gives me that error:
``````````````````````````````````````````````````````````````````````````````````````````````````````````````````
ERROR: Error executing Forestry.zs: null
java.lang.NullPointerException
	at modtweaker2.mods.forestry.handlers.Carpenter$Remove.getRecipeInfo(Carpenter.java:92)
	at modtweaker2.util.BaseListRemoval.describe(BaseListRemoval.java:62)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:50)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.forestry.handlers.Carpenter.removeRecipe(Carpenter.java:69)
	at Forestry.__script__(Forestry.zs:88)
	at __ZenMain__.run(Forestry.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````````````````````````````````````````````````````````````````````````````````````````````````````````````````

I try with other liquids too but gave me the same error.

My script

//Escritoir

//remove

mods.forestry.Carpenter.removeRecipe(<Forestry:core:1>);
//add
mods.forestry.Carpenter.addRecipe(600, <liquid:seedoil> * 500,  
[<minecraft:planks>, <gregtech:gt.metaitem.01:27809>, <gregtech:gt.metaitem.01:27809>, <minecraft:wooden_slab>, <minecraft:wooden_slab>, <minecraft:wooden_slab>, <minecraft:fence>, null, <minecraft:fence>], 
<Forestry:core:1>);


bdw. Adding Recipes to Thermionic Fabricator works well.

My full script (now i deleting the Carpenter Recipe)

https://github.com/Dream-Master/DreamCraft/blob/a0b29c238f8b2ae3d7f5968cc6e157e24b84c02d/scripts/Forestry.zs

**Comment by joshiejack** [comment]
You're missing a ingredient.

https://github.com/jaredlll08/ModTweaker2/blob/master/src/main/java/modtweaker2/mods/forestry/handlers/Carpenter.java#L27

**Comment by Dream-Master** [comment]
What ingredients you mean. If I am adding on the end,null) it don't working too.

**Comment by jaredlll08** [comment]
"a method available but none matches the parameters (int, any, any[],
minetweaker.item.IItemStack)" means that YOUR zenscript method is incorrect.
The correct method is:


int packagingTime, LiquidStack liquid, ItemStack[] ingredients, ItemStack
ingredient, ItemStack product

so,
mods.forestry.Carpenter.addRecipe(50, <liquid:water>, [<minecraft:planks>,
<gregtech:gt.metaitem.01:27809>, <gregtech:gt.metaitem.01:27809>,
<minecraft:wooden_slab>, <minecraft:wooden_slab>, <minecraft:wooden_slab>,
<minecraft:fence>, null, <minecraft:fence>], <minecraft:diamond>,
<minecraft:bedrock>);

**Comment by Dream-Master** [comment]
Yes Carpenter Recipes works well thanks for help.
