### ISSUE TITLE
[bug] cant remove Carpenters Recipes

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#77]
cant remove things from the carpenter.

//Escritoire
mods.forestry.Carpenter.removeRecipe(<Forestry:core:1>);

````````````````````````````````````````````````````````````````````````````````````````````````````````
ERROR: Error executing Forestry.zs: null
java.lang.NullPointerException
	at modtweaker2.mods.forestry.handlers.Carpenter$Remove.getRecipeInfo(Carpenter.java:92)
	at modtweaker2.util.BaseListRemoval.describe(BaseListRemoval.java:62)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:50)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.forestry.handlers.Carpenter.removeRecipe(Carpenter.java:69)
	at Forestry.__script__(Forestry.zs:90)
	at __ZenMain__.run(Forestry.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)`

``````````````````````````````````````````````````````````````````````````````````````````````````````````````

**Comment by Voidi** [comment]
thats because I failed, await fix soon

**Comment by Dream-Master** [comment]
ok thanks for quick answer.

**Comment by Voidi** [comment]
Here test it https://github.com/Voidi/ModTweaker2/releases/tag/1.2
If it works i make a pull reuqest.

**Comment by Dream-Master** [comment]
@Voidi 
gave me this Error with TestBuild 1.2

//remove

Usimg Code
//Escritoire
mods.forestry.Carpenter.removeRecipe(<Forestry:core:1>);

//add

//Escritoire
mods.forestry.Carpenter.addRecipe(600, <liquid:seedoil> * 500, [<minecraft:planks>,
<gregtech:gt.metaitem.01:27809>, <gregtech:gt.metaitem.01:27809>,
<minecraft:wooden_slab>, <minecraft:wooden_slab>, <minecraft:wooden_slab>,
<minecraft:fence>, null, <minecraft:fence>], null,
<Forestry:core:1>);

````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
ERROR: Error executing Forestry.zs: null
java.lang.NullPointerException
	at modtweaker2.mods.forestry.handlers.Carpenter$Remove.getRecipeInfo(Carpenter.java:92)
	at modtweaker2.util.BaseListRemoval.describe(BaseListRemoval.java:62)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:50)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.forestry.handlers.Carpenter.removeRecipe(Carpenter.java:69)
	at Forestry.__script__(Forestry.zs:88)
	at __ZenMain__.run(Forestry.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

````````````````````````````````````````````````````````````````````````````````````````````````````````````````

Arcane Recipes deletion works well now thanks.

**Comment by Dream-Master** [comment]
No it works. I using the last code from jaredlll08 and all my problems are solved. Arcane things work, Carpenters things too. Thanks
