### ISSUE TITLE
Not possible to join Multiplayer after Singleplayer

### ISSUE THREAD

**Issue by Voidi** [jaredlll08/ModTweaker2#87]
Client Log:
http://www.dertobi.name/~tobias/upload/Minecraft/fml-client-latest.log.disconnect

**Comment by jaredlll08** [comment]
Update modtweaker

**Comment by Voidi** [comment]
I am using the latest version

**Comment by jaredlll08** [comment]
You can't be... the issue links to a line of code I changed in the latest...

**Comment by Voidi** [comment]
i'm using Build 58, directly downloaded from Jenkins.

**Comment by jaredlll08** [comment]
Use the one from curseforge

**Comment by Voidi** [comment]
ok will test it, i assumed that git is the latest version

**Comment by Voidi** [comment]
Hm nope, seems not fixed

`[01:48:41] [Client thread/ERROR] [FML/]: SimpleChannelHandlerWrapper exception
java.lang.NullPointerException
	at modtweaker2.Commands.registerMineTweakerCommand(Commands.java:72) ~[Commands.class:?]
	at modtweaker2.Commands.registerCommands(Commands.java:30) ~[Commands.class:?]
	at modtweaker2.ModTweaker2$1.handle(ModTweaker2.java:106) ~[ModTweaker2$1.class:?]
	at modtweaker2.ModTweaker2$1.handle(ModTweaker2.java:102) ~[ModTweaker2$1.class:?]
	at minetweaker.util.EventList.publish(EventList.java:55) ~[EventList.class:?]
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:622) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.mc1710.network.MineTweakerLoadScriptsHandler.onMessage(MineTweakerLoadScriptsHandler.java:28) ~[MineTweakerLoadScriptsHandler.class:?]
	at minetweaker.mc1710.network.MineTweakerLoadScriptsHandler.onMessage(MineTweakerLoadScriptsHandler.java:21) ~[MineTweakerLoadScriptsHandler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) [SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) [DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) [DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) [EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper.jar:?]
[01:48:41] [Client thread/ERROR] [FML/]: There was a critical exception handling a packet on channel MineTweaker3
java.lang.NullPointerException
	at modtweaker2.Commands.registerMineTweakerCommand(Commands.java:72) ~[Commands.class:?]
	at modtweaker2.Commands.registerCommands(Commands.java:30) ~[Commands.class:?]
	at modtweaker2.ModTweaker2$1.handle(ModTweaker2.java:106) ~[ModTweaker2$1.class:?]
	at modtweaker2.ModTweaker2$1.handle(ModTweaker2.java:102) ~[ModTweaker2$1.class:?]
	at minetweaker.util.EventList.publish(EventList.java:55) ~[EventList.class:?]
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:622) ~[MineTweakerImplementationAPI.class:?]
	at minetweaker.mc1710.network.MineTweakerLoadScriptsHandler.onMessage(MineTweakerLoadScriptsHandler.java:28) ~[MineTweakerLoadScriptsHandler.class:?]
	at minetweaker.mc1710.network.MineTweakerLoadScriptsHandler.onMessage(MineTweakerLoadScriptsHandler.java:21) ~[MineTweakerLoadScriptsHandler.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:37) ~[SimpleChannelHandlerWrapper.class:?]
	at cpw.mods.fml.common.network.simpleimpl.SimpleChannelHandlerWrapper.channelRead0(SimpleChannelHandlerWrapper.java:17) ~[SimpleChannelHandlerWrapper.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:98) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:101) ~[SimpleChannelInboundHandler.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[MessageToMessageDecoder.class:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[MessageToMessageCodec.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.invokeChannelRead(DefaultChannelHandlerContext.java:337) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelHandlerContext.fireChannelRead(DefaultChannelHandlerContext.java:323) ~[DefaultChannelHandlerContext.class:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:785) ~[DefaultChannelPipeline.class:?]
	at io.netty.channel.embedded.EmbeddedChannel.writeInbound(EmbeddedChannel.java:169) ~[EmbeddedChannel.class:?]
	at cpw.mods.fml.common.network.internal.FMLProxyPacket.func_148833_a(FMLProxyPacket.java:77) [FMLProxyPacket.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.GuiConnecting.func_73876_c(SourceFile:78) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1649) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_76]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_76]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_76]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_76]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper.jar:?]`
