### ISSUE TITLE
Cant remove Rolling Machine Recipes (Railcraft)

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#89]
Get this error in the Minetweaker Log using Mod Tweaker 0.7.4

`````````````````````````````````````````````````````````````````````````
INFO: Removing Rolling Machine Recipe for :Rebar
ERROR: Error executing Railcraft.zs: null
java.lang.NullPointerException
	at modtweaker2.utils.BaseCraftingRemoval.apply(BaseCraftingRemoval.java:18)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.railcraft.handlers.RollingMachine.removeRecipe(RollingMachine.java:49)
	at Railcraft.__script__(Railcraft.zs:1463)
	at __ZenMain__.run(Railcraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````````````````````````````````````````````````````````````````````````````````````````````````````````````````

Remove code:

````````````````````````````````````````````````````````````````````````````````````
// --- Rebar ---
mods.railcraft.Rolling.removeRecipe(<Railcraft:part.rebar> * 2);
`````````````````````````````````````````````````````````````````````````````````````````

Other Recipes cant remove to only the adding function working.

After scripts reload the Game crash:

https://gist.github.com/Dream-Master/d958adbc83592b681cb0#file-gistfile1-txt

**Comment by Dream-Master** [comment]
With the old Version I compiled from the source of your Project everything works fine except this error occurs:

https://github.com/jaredlll08/ModTweaker2/issues/87

**Comment by Dream-Master** [comment]
Woks fine with Version 2-0.75

Thanks for the update!
