### ISSUE TITLE
Cant remove Thinkers Construct Table Recipe

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#90]
Get this error in the Minetweaker Log using Mod Tweaker 0.7.4

````````````````````````````````````````````````````````````````````````````````````````````````
ERROR: Error executing Tinkers-Construct.zs: null
java.lang.NullPointerException
	at modtweaker2.mods.tconstruct.handlers.Casting$Remove.apply(Casting.java:69)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.tconstruct.handlers.Casting.removeTableRecipe(Casting.java:56)
	at Tinkers-Construct.__script__(Tinkers-Construct.zs:147)
	at __ZenMain__.run(Tinkers-Construct.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

``````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````
Remove code:

// --- Aluminium Ingot Casting
mods.tconstruct.Casting.removeTableRecipe(<GalacticraftCore:item.basicItem:5>);`

After scripts reload the Game crash:

https://gist.github.com/Dream-Master/d958adbc83592b681cb0#file-gistfile1-txt

**Comment by Dream-Master** [comment]
With the old Version I compiled from the source of your Project everything works fine except this error occurs:
https://github.com/jaredlll08/ModTweaker2/issues/87

**Comment by Dream-Master** [comment]
I just find the error i hope.

**Comment by Dream-Master** [comment]
With the Old Version 0.7 it runs good with 0.74 i test it again and get me this error.

**Comment by Dream-Master** [comment]
Works fine with 2- 0.7.5

Thanks for the Update!
