### ISSUE TITLE
Can't remove recipes of the Railcraft Rolling Maschine. Modtweaker 0.7.4

### ISSUE THREAD

**Issue by Dream-Master** [jaredlll08/ModTweaker2#94]
Try to remove different Recipes in the Rolling Machine but with 0.74 it `didntwork.

```````````````````````````````````````````````````````````````````````````````````````````````````````````````
INFO: Removing Rolling Machine Recipe for :Iron Plate
ERROR: Error executing Railcraft.zs: null
java.lang.NullPointerException
	at modtweaker2.utils.BaseCraftingRemoval.apply(BaseCraftingRemoval.java:18)
	at minetweaker.runtime.MTTweaker.apply(MTTweaker.java:65)
	at minetweaker.MineTweakerAPI.apply(MineTweakerAPI.java:173)
	at modtweaker2.mods.railcraft.handlers.RollingMachine.removeRecipe(RollingMachine.java:49)
	at Railcraft.__script__(Railcraft.zs:1451)
	at __ZenMain__.run(Railcraft.zs)
	at minetweaker.runtime.MTTweaker.load(MTTweaker.java:157)
	at minetweaker.MineTweakerImplementationAPI.reload(MineTweakerImplementationAPI.java:624)
	at minetweaker.MineTweakerImplementationAPI$1.execute(MineTweakerImplementationAPI.java:82)
	at minetweaker.MineTweakerImplementationAPI$19.execute(MineTweakerImplementationAPI.java:610)
	at minetweaker.mc1710.server.MCServer$MCCommand.func_71515_b(MCServer.java:124)
	at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:94)
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:739)
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:718)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:37)
	at net.minecraft.network.play.client.C01PacketChatMessage.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
````````````````````````````````````````````````````````````````````````````````````````````````

**Comment by Dream-Master** [comment]
Works fine with Mod Tweaker 2-0.7.5

Thanks for the update!
